export const movies = [
  {
    id: 1,
    title: "Начало",
    description: "Вор, умеющий проникать в сны, получает задание внедрить идею в подсознание.",
    rating: 8.8,
    duration: 148,
    poster: "/posters/Начало.jpg",
    link: "https://www.kinopoisk.ru/film/447301/",
  },
  {
    id: 2,
    title: "Матрица",
    description: "Хакер узнаёт, что реальность — иллюзия, и вступает в борьбу с машинами.",
    rating: 8.7,
    duration: 136,
    poster: "/posters/Матрица.jpg",
    link: "https://www.kinopoisk.ru/film/301/",
  },
  {
    id: 3,
    title: "Интерстеллар",
    description: "Группа исследователей отправляется через червоточину в поисках нового дома для человечества.",
    rating: 8.6,
    duration: 169,
    poster: "/posters/Интерстеллар.jpg",
    link: "https://www.kinopoisk.ru/film/258687/",
  },
  {
    id: 4,
    title: "Темный рыцарь",
    description: "Бэтмен противостоит Джокеру, сеющему хаос в Готэме.",
    rating: 9.0,
    duration: 152,
    poster: "/posters/Темный рыцарь.jpg",
    link: "https://www.kinopoisk.ru/film/256/",
  },
  {
    id: 5,
    title: "Форрест Гамп",
    description: "История жизни простого человека, который становится свидетелем и участником важных событий.",
    rating: 8.8,
    duration: 142,
    poster: "/posters/Форрест Гамп.jpg",
    link: "https://www.kinopoisk.ru/film/326/",
  },
  {
    id: 6,
    title: "Бойцовский клуб",
    description: "Обычный человек создаёт подпольный клуб для борьбы с потребительским обществом.",
    rating: 8.8,
    duration: 139,
    poster: "/posters/Бойцовский клуб.jpg",
    link: "https://www.kinopoisk.ru/film/361/",
  },
  {
    id: 7,
    title: "Побег из Шоушенка",
    description: "История мужчины, несправедливо осуждённого и его попыток сбежать из тюрьмы.",
    rating: 9.3,
    duration: 142,
    poster: "/posters/Побег из Шоушенка.jpg",
    link: "https://www.kinopoisk.ru/film/435/",
  },
  {
    id: 8,
    title: "Властелин колец: Братство кольца",
    description: "Группа героев отправляется уничтожить могущественное кольцо.",
    rating: 8.8,
    duration: 178,
    poster: "/posters/Властелин колец Братство кольца.jpg",
    link: "https://www.kinopoisk.ru/film/326/",
  },
  {
    id: 9,
    title: "Звёздные войны: Новая надежда",
    description: "Молодой фермер становится героем в борьбе с Империей.",
    rating: 8.6,
    duration: 121,
    poster: "/posters/Звёздные войны Новая надежда.jpg",
    link: "https://www.kinopoisk.ru/film/447301/",
  },
  {
    id: 10,
    title: "Джокер",
    description: "История становления одного из самых известных злодеев комиксов.",
    rating: 8.4,
    duration: 122,
    poster: "/posters/Джокер.jpg",
    link: "https://www.kinopoisk.ru/film/1045452/",
  },
  {
    id: 11,
    title: "Паразиты",
    description: "Семья из бедного района внедряется в жизнь богатой семьи с неожиданными последствиями.",
    rating: 8.6,
    duration: 132,
    poster: "/posters/Паразиты.jpg",
    link: "https://www.kinopoisk.ru/film/1048060/",
  },
  {
    id: 12,
    title: "Гарри Поттер и философский камень",
    description: "Мальчик-волшебник начинает своё обучение в школе магии Хогвартс.",
    rating: 7.6,
    duration: 152,
    poster: "/posters/Гарри Поттер и философский камень.jpg",
    link: "https://www.kinopoisk.ru/film/257/",
  },
  {
    id: 13,
    title: "Титаник",
    description: "История любви на фоне трагедии затонувшего лайнера.",
    rating: 7.8,
    duration: 195,
    poster: "/posters/Титаник.jpg",
    link: "https://www.kinopoisk.ru/film/123/",
  },
  {
    id: 14,
    title: "Назад в будущее",
    description: "Подросток случайно отправляется в прошлое на машине времени.",
    rating: 8.5,
    duration: 116,
    poster: "/posters/Назад в будущее.jpg",
    link: "https://www.kinopoisk.ru/film/44731/",
  },
  {
    id: 15,
    title: "Гладиатор",
    description: "Римский генерал становится гладиатором и мстит за свою семью.",
    rating: 8.5,
    duration: 155,
    poster: "/posters/Гладиатор.jpg",
    link: "https://www.kinopoisk.ru/film/465/",
  },
  {
    id: 16,
    title: "В поисках Немо",
    description: "Рыбка-клоун отправляется на поиски своего сына.",
    rating: 8.1,
    duration: 100,
    poster: "/posters/В поисках Немо.jpg",
    link: "https://www.kinopoisk.ru/film/280/",
  },
  {
    id: 17,
    title: "Король Лев",
    description: "История львёнка, который должен стать королём саванны.",
    rating: 8.5,
    duration: 88,
    poster: "/posters/Король Лев.jpg",
    link: "https://www.kinopoisk.ru/film/3016/",
  },
  {
    id: 18,
    title: "Дюнкерк",
    description: "Эвакуация солдат с пляжей Дюнкерка во время Второй мировой войны.",
    rating: 7.9,
    duration: 106,
    poster: "/posters/Дюнкерк.jpg",
    link: "https://www.kinopoisk.ru/film/1047739/",
  },
  {
    id: 19,
    title: "Отступники",
    description: "Полицейский внедряется в мафию, а мафиози — в полицию.",
    rating: 8.5,
    duration: 151,
    poster: "/posters/Отступники.jpg",
    link: "https://www.kinopoisk.ru/film/362/",
  },
  {
    id: 20,
    title: "Ла-Ла Ленд",
    description: "История любви музыканта и актрисы в Лос-Анджелесе.",
    rating: 8.0,
    duration: 128,
    poster: "/posters/Ла-Ла Ленд.jpg",
    link: "https://www.kinopoisk.ru/film/942433/",
  },
];
