export const serials = [
  {
    id: 1,
    title: "Во все тяжкие",
    description: "Учитель химии становится наркобароном, чтобы обеспечить семью.",
    rating: 9.5,
    duration: 62,
    poster: "./posters/Во все тяжкие.jpg",
  },
  {
    id: 2,
    title: "Игра престолов",
    description: "Борьба за власть в фантастическом мире Вестерос.",
    rating: 9.3,
    duration: 73,
    poster: "./posters/Игра престолов.jpg",
  },
  {
    id: 3,
    title: "Очень странные дела",
    description: "Группа детей сталкивается с паранормальными событиями в маленьком городе.",
    rating: 8.7,
    duration: 34,
    poster: "./posters/Очень странные дела.jpg",
  },
  {
    id: 4,
    title: "Шерлок",
    description: "Современная адаптация приключений знаменитого детектива.",
    rating: 9.1,
    duration: 13,
    poster: "./posters/Шерлок.jpg",
  },
  {
    id: 5,
    title: "Черное зеркало",
    description: "Антология о темной стороне технологий и общества.",
    rating: 8.8,
    duration: 22,
    poster: "./posters/Черное зеркало.jpg",
  },
  {
    id: 6,
    title: "Нарко",
    description: "История жизни и падения колумбийского наркобарона Пабло Эскобара.",
    rating: 8.8,
    duration: 30,
    poster: "./posters/Нарко.jpg",
  },
  {
    id: 7,
    title: "Фарго",
    description: "Криминальная драма с черным юмором в духе одноименного фильма.",
    rating: 8.9,
    duration: 40,
    poster: "./posters/Фарго.jpg",
  },
  {
    id: 8,
    title: "Лучше звоните Солу",
    description: "Приключения адвоката Джимми МакГилла до событий Во все тяжкие.",
    rating: 8.7,
    duration: 63,
    poster: "./posters/Лучше звоните Солу.jpg",
  },
  {
    id: 9,
    title: "Друзья",
    description: "Жизнь и приключения шестерых друзей в Нью-Йорке.",
    rating: 8.9,
    duration: 236,
    poster: "./posters/Друзья.jpg",
  },
  {
    id: 10,
    title: "Настоящий детектив",
    description: "Антология криминальных историй с глубоким психологизмом.",
    rating: 9.0,
    duration: 24,
    poster: "./posters/Настоящий детектив.jpg",
  },
  {
    id: 11,
    title: "Викинги",
    description: "Истории легендарных скандинавских воинов и их завоеваний.",
    rating: 8.6,
    duration: 89,
    poster: "./posters/Викинги.jpg",
  },
];