export const serials = [
  {
    id: 21,
    title: "Во все тяжкие",
    description: "Учитель химии становится наркобароном, чтобы обеспечить семью.",
    rating: 9.5,
    duration: 62,
    poster: "/posters/Во все тяжкие.jpg",
    link: "https://www.kinopoisk.ru/series/15856/",
  },
  {
    id: 22,
    title: "Игра престолов",
    description: "Борьба за власть в фантастическом мире Вестерос.",
    rating: 9.3,
    duration: 73,
    poster: "/posters/Игра престолов.jpg",
    link: "https://www.kinopoisk.ru/series/435/",
  },
  {
    id: 23,
    title: "Очень странные дела",
    description: "Группа детей сталкивается с паранормальными событиями в маленьком городе.",
    rating: 8.7,
    duration: 34,
    poster: "/posters/Очень странные дела.jpg",
    link: "https://www.netflix.com/title/80057281", // Netflix
  },
  {
    id: 24,
    title: "Шерлок",
    description: "Современная адаптация приключений знаменитого детектива.",
    rating: 9.1,
    duration: 13,
    poster: "/posters/Шерлок.jpg",
    link: "https://www.kinopoisk.ru/series/295/",
  },
  {
    id: 25,
    title: "Черное зеркало",
    description: "Антология о темной стороне технологий и общества.",
    rating: 8.8,
    duration: 22,
    poster: "/posters/Черное зеркало.jpg",
    link: "https://www.netflix.com/title/70264888",
  },
  {
    id: 26,
    title: "Нарко",
    description: "История жизни и падения колумбийского наркобарона Пабло Эскобара.",
    rating: 8.8,
    duration: 30,
    poster: "/posters/Нарко.jpg",
    link: "https://www.netflix.com/title/80025172",
  },
  {
    id: 27,
    title: "Фарго",
    description: "Криминальная драма с черным юмором в духе одноименного фильма.",
    rating: 8.9,
    duration: 40,
    poster: "/posters/Фарго.jpg",
    link: "https://www.imdb.com/title/tt2802850/",
  },
  {
    id: 28,
    title: "Лучше звоните Солу",
    description: "Приключения адвоката Джимми МакГилла до событий Во все тяжкие.",
    rating: 8.7,
    duration: 63,
    poster: "/posters/Лучше звоните Солу.jpg",
    link: "https://www.kinopoisk.ru/series/1044737/",
  },
  {
    id: 29,
    title: "Друзья",
    description: "Жизнь и приключения шестерых друзей в Нью-Йорке.",
    rating: 8.9,
    duration: 236,
    poster: "/posters/Друзья.jpg",
    link: "https://www.imdb.com/title/tt0108778/",
  },
  {
    id: 30,
    title: "Настоящий детектив",
    description: "Антология криминальных историй с глубоким психологизмом.",
    rating: 9.0,
    duration: 24,
    poster: "/posters/Настоящий детектив.jpg",
    link: "https://www.hbo.com/true-detective",
  },
  {
    id: 31,
    title: "Викинги",
    description: "Истории легендарных скандинавских воинов и их завоеваний.",
    rating: 8.6,
    duration: 89,
    poster: "/posters/Викинги.jpg",
    link: "https://www.imdb.com/title/tt2306299/",
  },
];